source 'https://rubygems.org'

gem "git",        "~> 1.2.7"
gem "thor",       "~> 0.18.1"
gem "paint",      "~> 0.8.6"
gem "icalendar",  "~> 2.1.0"

group :development do
  #gem 'libnotify'
  #gem 'guard-rspec'
  gem 'rspec'
end
