source 'https://rubygems.org'

gem "git",        "~> 1.2"
gem "thor",       "~> 0.19.1"
gem "paint",      "~> 0.8.7"
gem "icalendar",  "~> 2.1.1"
gem 'euro',       '~> 0.3'

group :development do
  gem 'libnotify'
  gem 'guard-rspec'
  gem 'rspec'
end
