# A sample Guardfile
# More info at https://github.com/guard/guard#readme

#guard :rspec, :cli => "--color --format nested --fail-fast --drb" do
guard :rspec, :cli => "--color " do
  notification :libnotify, :timeout => 5, :transient => true, :append => false, :urgency => :critical
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end

